name: Reusable workflow for General Main Branches

on:
  workflow_call:
    secrets:
      repo_username:
        required: true
      repo_token:
        required: true
    inputs:
      app_name:
        required: true
        type: string
      context:
        required: true
        type: string
      repo:
        required: true
        type: string

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.repo_username }}
          password: ${{ secrets.repo_token }}
      - name: Get smart tag
        id: prepare
        uses: Surgo/docker-smart-tag-action@v1
        with:
          docker_image: ${{ inputs.repo }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.prepare.outputs.tag }}
          context: "{{defaultContext}}:${{ inputs.context }}"

