name: Reusable workflow for General Main Branches

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      context:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: andersondario/${{ inputs.app_name }}:${{ inputs.tag }}
          context: "{{defaultContext}}:${{ inputs.context }}"

